apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejsprom
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: nodejsprom
  template:
    metadata:
      labels:
        app: nodejsprom
    spec:
      containers:
        - image: m1nase/promtest1:latest
          name: nodejsprom
