# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

jobs:
  &common-job-settings
  docker:
    - image: cimg/base:stable
  steps:
    - checkout

  say-hello:
    <<: *common-job-settings
    - run:
        name: "Say hello"
        command: "echo Hello, World!"

  say-goodbye:
    <<: *common-job-settings
    - run:
        name: "Say goodbye"
        command: "echo Goodbye, World!"

# Orchestrate jobs using workflows
# See: https://circleci.com/docs/configuration-reference/#workflows
workflows:
  say-hello-workflow:
    jobs:
      - say-hello
          filters:
            branches:
              ignore:
                - "*"
            tags:
              ignore:
                - "*"
            pull-requests:
              ignore: true
      - say-goodbye:
          requires:
            - say-hello