apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejsot
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: nodejsot
  template:
    metadata:
      labels:
        app: nodejsot
    spec:
      containers:
        - image: m1nase/ottest1:latest
          name: nodejsot
