apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: '0'
    argocd-image-updater.argoproj.io/image-list: ng=nginx:*
    argocd-image-updater.argoproj.io/write-back-method: git
    argocd-image-updater.argoproj.io/git-branch: main
    argocd-image-updater.argoproj.io/write-back-target: kustomization
    argocd-image-updater.argoproj.io/ng.force-update: 'true'
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    path: apps/nginx
    repoURL: https://github.com/Esanim/auto-updater-test.git
    targetRevision: main
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    syncOptions:
      - PruneLast=true
      - FailOnSharedResource=true
      - CreateNamespace=false
    automated:
      prune: true
      selfHeal: true
