apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: '2'
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: monitoring
    server: https://kubernetes.default.svc
  project: default
  source:
    path: apps/prometheus
    repoURL: https://github.com/Esanim/auto-updater-test.git
    targetRevision: main
  syncPolicy:
    syncOptions:
      - PruneLast=true
      - FailOnSharedResource=true
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
