apiVersion: v1
kind: Service
metadata:
  name: prometheus-server
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/port: '81'
spec:
  type: NodePort
  selector:
    app: prometheus-server
  ports:
    - port: 81
      targetPort: 9090
      protocol: TCP
