name: 'Lint PR'

on:
  push:
    branches:
      - 'main'

jobs:
  main:
    name: Validate PR title
    runs-on: ubuntu-latest

    permissions:
      pull-requests: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - id: zip
        run: |
          zip -r test.zip apps/nginx/

      - id: echo
        run: echo ${{ secrets.sec }}

      - id: echo2
        run: echo ${{ secrets.nml }}
