name: 'Lint PR'

on:
  push:
    branches:
      - 'main'

jobs:
  main:
    name: Validate PR title
    runs-on: ubuntu-latest

    permissions:
      pull-requests: write

    steps:
      - id: zip
        run: |
          zip -r test.zip apps/nginx
